version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wilofo_api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./opcache.ini:/usr/local/etc/php/conf.d/opcache.ini 
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=wilofo_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - TELEGRAM_BOT_TOKEN=7811367126:AAG96AufIO1EwJa2SQIGkYD7dISlLZSBg80
      - TELEGRAM_CHAT_ID=634825037
    depends_on:
      - db
      - redis
    networks:
      - wilofo_network

  db:
    image: mysql:8.0
    container_name: wilofo_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wilofo_db
      #MYSQL_USER: enumera_test
      #MYSQL_PASSWORD: enumera_test
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf 
    networks:
      - wilofo_network

  redis:
    image: redis:alpine
    container_name: wilofo_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - wilofo_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wilofo_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=50M
    ports:
      - "8081:80"
    networks:
      - wilofo_network
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: wilofo_phpredisadmin
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_1_HOST=redis
    ports:
      - "8082:80"
    networks:
      - wilofo_network
  worker:
    build: .
    container_name: wilofo_worker
    restart: always
    working_dir: /var/www/html
    networks:
      - wilofo_network
    depends_on:
      - redis
    volumes:
      - .:/var/www/html:cached
    command: supervisord -c /etc/supervisor/supervisord.conf

networks:
  wilofo_network:
    driver: bridge

volumes:
  dbdata:
