# Utiliser l'image officielle de PHP 8.2 avec Apache
FROM php:8.2-apache

# Installer les dépendances système et extensions PHP requises
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl \
    libzip-dev \
    supervisor \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip pcntl opcache

# Installer Composer globalement
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier uniquement les fichiers de configuration Composer
COPY composer.json composer.lock ./

# Copier le contenu du projet dans /var/www/html
COPY . ./

# Installer les dépendances PHP AVANT de copier tout le projet
RUN composer install --optimize-autoloader --no-dev

# Copier la configuration OPCache
COPY opcache.ini /usr/local/etc/php/conf.d/opcache.ini



# Configurer les permissions pour Laravel (pour Apache)
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html \
    && chmod -R 755 /var/www/html/storage \
    && chmod -R 755 /var/www/html/bootstrap/cache

# Changer le DocumentRoot d'Apache pour pointer vers le dossier public de Laravel
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# Activer le module mod_rewrite d'Apache pour supporter les URLs propres de Laravel
RUN a2enmod rewrite

# Copier la configuration de Supervisord
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Exposer le port 80 pour Apache
EXPOSE 80

# Démarrer Supervisord pour exécuter Apache et Horizon
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
